# Setup
title:        mocker-data-generator
tagline:      A simplified way to generate masive mock data based on a schema, using the awesome fake/random data generators like (FakerJs, ChanceJs, CasualJs and RandExpJs), all in one tool to generate your fake data for testing
baseurl:      mocker-data-generator
paginate:     1
url:          https://github.com/danibram/mocker-data-generator

# About/contact
author:
  name:       Daniel Biedma
  url:        http://github.com/danibram
  email:      info@dbr.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
